service:
    - start: 2014
      role: Panel member
      entity: "Guardian Sustainable Business live chat on \\href{http://www.theguardian.com/sustainable-business/energy-efficiency-commercial-properties-live-chat}{energy efficiency in non-domestic buildings}"
grant_reviews:
  - Engineering and Physical Sciences Research Council
journal_reviews:
  - Energy Policy
consultancy:
  - Environmental Change Institute, University of Oxford (Carbon Trust, Department for International Development)
