service:
    - start: 2014
      role: Panel member
      entity: "Guardian Sustainable Business live chat on \\href{http://www.theguardian.com/sustainable-business/energy-efficiency-commercial-properties-live-chat}{energy efficiency in non-domestic buildings}"
    - start: 2014
      role: Steering group member
      entity: Energy Research Partnership Cities project
    - start: 2014
      role: Programme committee member
      entity: First International Workshop on Demand Response (DR2014).
    - start: 2013
      role: Invited participant
      entity: EPSRC Engineering Leaders of the Future. October, Hellidon Lakes.
    - start: 2013
      role: Invited participant
      entity: Research Councils UK energy strategy workshop on energy infrastructure.  Birmingham.
    - start: 2013
      role: Technical committee member
      entity: International Society for Industrial Ecology conference
    - start: 2015
      role: Technical committee member
      entity: International Society for Industrial Ecology conference
    - start: 2011
      end: present
      role: Board member
      entity: Sustainable Urban Systems section, International Society for Industrial Ecology.
    - start: 2011
      end: 2012
      role: Technical advisory panel member
      entity: Challenging Lock-in Through Urban Energy Systems EPRSC project
    - start: 2011
      end: 2012
      role: Technical committee member
      entity: CIBSE ASHRAE Technical Symposium      
    - start: 2011
      end: 2013
      role: Programme committee member
      entity: 2nd--4th International Workshops on Agent Technologies for Energy Systems (ATES)
    - start: 2010
      role: Reviewer
      entity: ECOS and Next Generation Infrastructures conferences
    - start: 2009
      role: Invited participant
      entity: EPSRC Grand Challenge workshop on Sustainable Urban Environments
grant_reviews:
  - Engineering and Physical Sciences Research Council
  - Economic and Social Research Council
  - US National Science Foundation
  - Natural Sciences and Engineering Research Council of Canada
  - Social Sciences and Humanities Research Council of Canada
  - Paul Scherrer Institute
journal_reviews:
  - Energy Policy
  - Proceedings of the National Academy of Sciences
  - Building Research and Information
  - Technological Forecasting and Social Change
  - Energy
  - Energy Economics
  - Environmental Practice
  - Journal of Artificial Societies and Social Simulation
  - Energy Efficiency
  - "Sustainable: Science, Practice and Policy"
  - The Energy Journal
  - Journal of Industrial Ecology
  - Computers, Environment and Urban Systems
  - Journal of Urban Technology
  - International Journal of Sustainable Transportation
  - Climatic Change
  - Urban Design and Planning
  - Environmental Science & Technology
  - IET Renewable Power Generation
  - Environment and Planning B
  - Ecological Modelling
  - Environmental Research Letters
  - Journal of Environmental Planning and Management
  - Cities
  - Sustainability Science
  - Urban Studies
  - Journal of Professional Issues in Engineering Education and Practice
  - Solutions
  - Civil Engineering and Environmental Systems
  - Building and Environment
  - Sustainable Cities and Society
consultancy:
  - Environmental Change Institute, University of Oxford (Carbon Trust, Department for International Development)
  - Government Office for Science Foresight (Sustainable Energy Management in the Built Environment, Future of Cities)
  - International Institute for Applied Systems Analysis
  - EDF/Weber Shandwick
  - The Economist Group
  - Energy Technologies Institute
  - Arup
  - University of Toronto/Enel Foundation
